omnivector-solutions/osd-documentation

operations/partitions.rst

add example on how to add another partition
fix #26

Improve the partition operations

---

installation.rst
operations/monitoring.rst
operations/overview.rst

Depends on https://github.com/omnivector-solutions/slurm-bundles/pull/19
online at: https://omnivector-solutions.github.io/osd-documentation/testing/

add section for cluster monitoring

---

contributing.rst

Depends on omnivector-solutions/slurm-charms#114

Mention the etcd resource

---

installation.rst

Docs for https://github.com/omnivector-solutions/slurm-charms/pull/115
Online at: https://omnivector-solutions.github.io/osd-documentation/testing/installation.html#deploy-slurm

Document the omnivector ubuntu PPA

---

operations/nodes.rst

operations/nodes: warn user for initial setup

---

operations/nodes.rst

Online: https://omnivector-solutions.github.io/osd-documentation/testing/operations/nodes.html#removing-nodes
fix #24

operations/nodes: add a warning to removing

---

operations/installation.rst
operations/overview.rst

Explain the custom-slurm-repo

---

.github/workflows/publish.yaml
operations/logging.rst
operations/overview.rst

Online: https://omnivector-solutions.github.io/osd-documentation/testing/operations/logging.html

Operations: add logging instructions with Fluentbit

---

acknowledgements.rst
index.rst

https://omnivector-solutions.github.io/osd-documentation/testing/acknowledgements.html

WIP: add acknowledgements page

---

operations/infiniband.rst

Add a note on how to reboot nodes and check infiniband capabilities
Solves #27

infiniband: document how to reboot and check link

---

acknowledgements.rst

Big thanks to
- Dmitrii Shcherbakov
- Johan Hallbäck
- Zoltan Zeestraten

acknowledgements: community contributions

---

acknowledgements.rst

Hi, thanks for the acknowledgement. I would appreciate if you could fix the name.

Fix name in acknowledgements.rst

---

index.rst
installation.rst
operations/accounting-profiling.rst
operations/nodes.rst
operations/overview.rst

Documentation for https://github.com/omnivector-solutions/slurm-charms/pull/131
Online at: https://omnivector-solutions.github.io/osd-documentation/testing/operations/accounting-profiling.html#elasticsearch-plugin

operations:accounting: add elastic search addon

---

architecture.rst

Online at: https://omnivector-solutions.github.io/osd-documentation/testing/architecture.html#osd-components

architecture: add charms badges

---

operations/gpu.rst
operations/overview.rst

Online at: https://omnivector-solutions.github.io/osd-documentation/testing/operations/gpu.html

Initial docs for GPU support

---

index.rst

Online at: https://omnivector-solutions.github.io/osd-documentation/testing/

index: add OSD demo to front page

---

operations/infiniband.rst

slurm-charms now provide ofed 5.4
Depends on https://github.com/omnivector-solutions/slurm-charms/pull/143

operations:infiniband: update version

---

installation.rst
operations/installation.rst

Online at https://omnivector-solutions.github.io/osd-documentation/testing/operations/installation.html
Solves ASP-1634

Extend the notes about using custom repo for Slurm

---

new_words_spell_checker.txt
operations/overview.rst
operations/singularity.rst

Add a documentation about the singularity installation in the slurmd charm.

Add documentation about singularity installation

---

architecture.rst
operations/monitoring.rst
operations/nhc.rst

Documentation for https://github.com/omnivector-solutions/slurm-charms/pull/151

Modify documentation about NHC installation

---

README.md
contributing.rst

Improve text in the contributing guide around git usage and the release process.

Enhance contributing guide

---

new_words_spell_checker.txt
operations/mpi.rst
operations/overview.rst

Add a documentation about the MPI (mpich implementation) installation action in slurmd.

Add documentation about MPI installation
